#+title: Git - Tree Objects
#+roam_tags: git objects tree

Tree objects.

* Lab | ~C-c on the property string first!~

#+property: header-args :dir /Users/allarm/Tmp/git_lab_1 :results output drawer 

** Clean it up | ~execute it first~

#+begin_src bash 
case $(pwd) in
,*git_lab_1*)
    cd ..
    rm -rf git_lab_1
    mkdir git_lab_1
    cd git_lab_1
    pwd
    ls -al
    ;;
,*)
    echo "You're in a wrong directory pal: $(pwd)."
    ;;
esac
#+end_src

#+RESULTS:
:results:
/Users/allarm/Tmp/git_lab_1
total 0
drwxr-xr-x   2 allarm  staff   64 Nov 10 17:20 .
drwxr-xr-x  23 allarm  staff  736 Nov 10 17:20 ..
:end:

** Set it up

#+begin_src bash
echo "Hello world!" > hello.txt
echo "Goodbye world :(" > goodbye.txt
mkdir awesome_dir
echo "I am awesome!" > awesome_dir/awesome.txt
git init
git config user.name "Andrey Che"
git config user.email "andrey@che.org"
git add .
git commit -m "First commit"
#+end_src

#+RESULTS:
:results:
Initialized empty Git repository in /Users/allarm/Tmp/git_lab_1/.git/
[master (root-commit) e03395e] First commit
 3 files changed, 3 insertions(+)
 create mode 100644 awesome_dir/awesome.txt
 create mode 100644 goodbye.txt
 create mode 100644 hello.txt
:end:

** Let's roll

Let's get the file objects:

#+begin_src bash
objects=$(find .git/objects -type f | awk -F"/" '{print $3$4}')
for o in $objects
do
  echo "$o : $(git cat-file -t $o)"
done
#+end_src

#+RESULTS:
:results:
ed557584085e6ecbc79a01adb943fdba7a05f5f0 : tree
c12fddafdaba3b7b1281f50c9e482ed673f1767c : blob
27c68820a14130e9866371d6cb746ca5cbd39864 : tree
11dd309e25ce41320f8b55ef3be7d50246a8b4a6 : blob
cd0875583aabe89ee197ea133980a9085d08e497 : blob
e03395ec8b3f4b9c1321622e3f56d181038adf82 : commit
:end:

Now let's take a loot at the contents of the =tree= objects.

#+begin_src bash
objects=$(find .git/objects -type f | awk -F"/" '{print $3$4}')
for o in $objects
do
  type=$(git cat-file -t $o)
  if [ $type == "tree" ]
  then
    echo "[ $o : $type ]"
    echo
    git cat-file -p $o
    echo
  fi
done
#+end_src

#+RESULTS:
:results:
[ ed557584085e6ecbc79a01adb943fdba7a05f5f0 : tree ]

100644 blob 11dd309e25ce41320f8b55ef3be7d50246a8b4a6	awesome.txt

[ 27c68820a14130e9866371d6cb746ca5cbd39864 : tree ]

040000 tree ed557584085e6ecbc79a01adb943fdba7a05f5f0	awesome_dir
100644 blob c12fddafdaba3b7b1281f50c9e482ed673f1767c	goodbye.txt
100644 blob cd0875583aabe89ee197ea133980a9085d08e497	hello.txt

:end:

There are 2 =tree= objects in the repo. One is pointing to the file in the =awesome_dir= and another points to the files in the root dir *and* to the first tree object.

If we commited the changes the [[file:git_commit_objects.org][commit object]] would point to the second tree object.
